version: 2.1

jobs:
  build_application:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install
      - run:
          name: Run Build
          command: |
            npm run build

  deploy_backend:
    docker:
      - image: circleci/node:latest
    resource_class: medium
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:dTbd7DeoUsp6E6cpOm1sufbJLEs3Hnglp4PTX+/2vBc"
      - checkout
      - run:
          name: Deploy Backend
          command: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa ubuntu@65.2.130.131   \
            "cd /var/www/html/React_Cicd  && \
            git reset --hard HEAD && \
            sudo git pull origin main && \
            pwd"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_application
      - deploy_backend:
          requires:
            - build_application
          filters:
            branches:
              only:
                - main
