version: 2.1

jobs:
  build_application:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy_backend:
    docker:
      - image: circleci/node:latest
    resource_class: medium
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:dTbd7DeoUsp6E6cpOm1sufbJLEs3Hnglp4PTX+/2vBc"
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy Backend
          command: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa ubuntu@65.2.130.131 << EOF
              cd /var/www/html/React_Cicd
              sudo git reset --hard HEAD
              sudo git pull origin main
              sudo npm install
              sudo npm run build
              sudo systemctl reload apache2
              sudo chown -R ubuntu:ubuntu .
              EOF

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_application
      - deploy_backend:
          requires:
            - build_application
          filters:
            branches:
              only:
                - main
